# Generated by Django 4.2.7 on 2024-06-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Whatapp_Reminder_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
